name: Deploy

on:
  push:
    branches:
      - 'main'

env:
  REGISTRY: ghcr.io

jobs:
  build-authen:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to GitHub Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/ewancoder/tyr-authen

      - name: Build and push Authen Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          file: Tyr.Authen/Dockerfile
          target: final
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: [build-authen]

    permissions:
      contents: read

    steps:
      - name: Deploy to DO
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          passphrase: ${{ secrets.PASSWORD }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            curl https://raw.githubusercontent.com/ewancoder/tyr-authen/main/docker-compose-production.yml > /tmp/tyr-authen-docker-compose.yml
            docker compose -f /tmp/tyr-authen-docker-compose.yml pull
            docker compose -f /tmp/tyr-authen-docker-compose.yml up -d
